In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [2]:
from sklearn.datasets import load_digits

In [3]:
digits=load_digits()

In [4]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

## KFold cross validation
### Basic Example

In [5]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [6]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


## cross_val_score function

In [7]:
X=digits.data
Y=digits.target

In [8]:
from sklearn.model_selection import cross_val_score

In [9]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),X,Y, cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [10]:
cross_val_score(SVC(gamma='auto'),X,Y, cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [11]:
cross_val_score(RandomForestClassifier(n_estimators=40), X,Y, cv=3)

array([0.92654424, 0.93989983, 0.93322204])

## Parameter tunning using k fold cross validation

In [12]:
import numpy as np

In [13]:
score1=cross_val_score(RandomForestClassifier(n_estimators=10), X,Y, cv=10)
np.average(score1)

0.9143171942892613

In [14]:
score2=cross_val_score(RandomForestClassifier(n_estimators=20), X,Y, cv=10)
np.average(score2)

0.9354407200496586

In [15]:
score3=cross_val_score(RandomForestClassifier(n_estimators=30), X,Y, cv=10)
np.average(score3)

0.9421353196772191

In [16]:
score4=cross_val_score(RandomForestClassifier(n_estimators=40), X,Y, cv=10)
np.average(score4)

0.9376691495965238

In [17]:
score5=cross_val_score(RandomForestClassifier(n_estimators=50), X,Y, cv=10)
np.average(score5)

0.9449037864680323